### ISSUE TITLE
urllib3 version

### ISSUE THREAD

**Issue by theguly** [sensepost/reGeorg#10]
hi, using reGeorg on kali linux i have this error:
[ERROR  ]  'HTTPConnectionPool' object has no attribute 'close'

digging a bit it seems an outdated version of urllib3 (kali ships 1.3-3), the issue has been fixed installing urllib3 using pip

do you think urllib3 version should be mentioned in requirements list or can you handle this code-side?

thanks

**Comment by joda32** [comment]
Hi,

firstly thx for using reGeorg, i hope you find it helpful :) yes it seems
the there are some version of urllib that have problem and i'm actually
working on a new version that uses some custom http code to add to
stability and performance.
but in the meantime i think ill add some notes to the docs on potential
issues on kali.

thnx again

**Comment by theguly** [comment]
of course reGeorg is very useful :)
thanks for your reply
